In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('IRIS.csv')
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [4]:
selected_columns = data[['sepal_length','sepal_width']]
print(selected_columns)

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]


In [5]:
filtered_data = data[data['sepal_length']>5]
print(filtered_data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[118 rows x 5 columns]


In [18]:
grouped_data = data.groupby('species')['sepal_length'].sum()
print(grouped_data)

species
Iris-setosa        250.3
Iris-versicolor    296.8
Iris-virginica     329.4
Name: sepal_length, dtype: float64


In [26]:
data1 = pd.read_csv('IRIS.csv')
data2 = pd.read_csv('IRIS.csv')
merged_data = pd.merge(data1,data2,on='sepal_width')
print(merged_data)

      sepal_length_x  sepal_width  petal_length_x  petal_width_x  \
0                5.1          3.5             1.4            0.2   
1                5.1          3.5             1.4            0.2   
2                5.1          3.5             1.4            0.2   
3                5.1          3.5             1.4            0.2   
4                5.1          3.5             1.4            0.2   
...              ...          ...             ...            ...   
1763             6.1          2.6             5.6            1.4   
1764             6.1          2.6             5.6            1.4   
1765             6.1          2.6             5.6            1.4   
1766             6.1          2.6             5.6            1.4   
1767             6.1          2.6             5.6            1.4   

           species_x  sepal_length_y  petal_length_y  petal_width_y  \
0        Iris-setosa             5.1             1.4            0.2   
1        Iris-setosa             5.1     

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [29]:
data.fillna(0,inplace=True)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [41]:
def process_value(value):
    processed_value = value*2
    return processed_value
data['processed_column'] = data['sepal_length'].apply(process_value)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_column  
0                10.2  
1                 9.8  
2  

In [43]:
pivot_table = pd.pivot_table(data,values='sepal_length',index='sepal_width',columns='species')
print(pivot_table)

species      Iris-setosa  Iris-versicolor  Iris-virginica
sepal_width                                              
2.0                  NaN         5.000000             NaN
2.2                  NaN         6.100000        6.000000
2.3             4.500000         5.600000             NaN
2.4                  NaN         5.300000             NaN
2.5                  NaN         5.625000        5.900000
2.6                  NaN         5.666667        6.900000
2.7                  NaN         5.680000        6.075000
2.8                  NaN         6.150000        6.475000
2.9             4.400000         6.085714        6.800000
3.0             4.700000         5.950000        6.716667
3.1             4.820000         6.766667        6.725000
3.2             4.680000         6.433333        6.760000
3.3             5.050000         6.300000        6.566667
3.4             5.033333         6.000000        6.250000
3.5             5.150000              NaN             NaN
3.6           

In [47]:
data['date_column'] = pd.to_datetime(data['sepal_length'])
data.set_index('date_column',inplace=True)
resampled_data = data.resample('M').sum()
print(resampled_data)

             sepal_length  sepal_width  petal_length  petal_width  \
date_column                                                         
1970-01-31          876.5        458.1         563.8        179.8   

             processed_column  
date_column                    
1970-01-31             1753.0  


C:\Users\USER\AppData\Local\Temp\ipykernel_3864\688559514.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  resampled_data = data.resample('M').sum()


In [46]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print("Sum ", np.sum(arr))
print("Mean ",np.mean(arr))
print("Max ",np.max(arr))
print("Min ",np.min(arr))

[1 2 3 4 5]
Sum  15
Mean  3.0
Max  5
Min  1


In [50]:
arr1 = np.array([1,2,3,4,5,6])
reshaped_arr = arr1.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [56]:
arr2 = np.random.random((3,3))
print(arr2)

[[0.85376724 0.54744441 0.90808516]
 [0.22034774 0.80733175 0.21921334]
 [0.77625176 0.31815754 0.21127992]]


In [57]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
print(arr3+arr4)

[5 7 9]


In [58]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
sum_along_rows = np.sum(arr5,axis=0)
sum_along_columns = np.sum(arr5,axis=1)
print(sum_along_rows)
print(sum_along_columns)

[12 15 18]
[ 6 15 24]


In [62]:
#Masking is a way of hiding elements in an array
arr6 = np.array([1,2,3,4,5])
print(arr6[1])
mask = arr > 2
filtered_arr = arr6[mask]
print(filtered_arr)

2
[3 4 5]


In [66]:
arr7 = np.array([1,1,2,2,3,3,3,4,4,4,4,5])
unique_element = np.unique(arr7)
element_occur = np.bincount(arr7)
print(unique_element)
print(element_occur)

[1 2 3 4 5]
[0 2 2 3 4 1]


In [68]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])
coefficients = np.polyfit(x,y,1)
slope,intercept = coefficients
print("Slope: ",slope)
print("Intercept: ",intercept)

Slope:  0.6000000000000002
Intercept:  2.1999999999999993
